variables:
  GIT_STRATEGY: clone
  FF_ENABLE_BASH_EXIT_CODE_CHECK: "true"

default:
  interruptible: true

stages:
- build
- publish

build:
  stage: build
  image: node:14
  script:
    - yarn install
  artifacts:
    expire_in: 1 week
    paths:
      - lib

publish:
  stage: publish
  image: debian:buster
  before_script:
    - apt-get update
    - apt-get install -y curl git jq build-essential python3 python3-pip zip
    - pip3 install --upgrade pip setuptools
    - pip3 install --upgrade httpie
    - http --ignore-stdin --check-status --print=b --download https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
    - export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
    - \. "$NVM_DIR/nvm.sh"
    - nvm install 14
    - nvm use 14
    - npm install -g yarn
    - npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
    - git remote set-url origin "https://$GITHUB_TOKEN@github.com/Mapwize/mapwize-sdk-react-native.git"
    - git config --global user.email "maxime.colmant@gmail.com"
    - git config --global user.name "Maxime Colmant"
    - yarn install
  script:
    - ./ci/publish-script.sh
  dependencies:
    - build
  only:
    - tags
