language: node_js
node_js:
  - 14
before_deploy:
  - ./fixNpmVersion.sh
  - yarn install
  - yarn docsPublish
  - zip -r tsdocs.zip docs_html || travis_terminate 1;
deploy:
  - provider: npm
    email: 'support@mapwize.io'
    api_key: '${NPM_TOKEN}'
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    api_key: '${GITHUB_TOKEN}'
    file: './tsdocs.zip'
    skip_cleanup: true
    on:
      tags: true
