language: node_js
node_js:
  - 14
before_deploy:
  - ./fixNpmVersion.sh
  - yarn install
  - yarn docsPublish
  - zip -r tsdocs.zip docs_html || travis_terminate 1;
deploy:
  - provider: npm
    email: 'support@mapwize.io'
    api_key: '${NPM_TOKEN}'
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    api_key: '${GITHUB_TOKEN}'
    file: './tsdocs.zip'
    skip_cleanup: true
    on:
      tags: true
env:
  global:
    secure: ZzVgtwNTQRF/yz+76uNFgLO+bPtM5CqttvYIrTyf9JNfHBop9hQyb3Ey+0wqYYrTKLXx8zlUYwWtrkpbiXLwhNS6J6NQK3UV/bPbHdG/Zm+AvF48TWEBPZri8cxj7pil966vNRAxZqwfjZ3wLeEYCrItGx4CzuYbhkvzC+zSiBQzhXrewCeW1P+uMvKA0sskZD4sKHOyYnrfy3y9cavLn/surh+7Kfc1DeOdzGt5o9+p8kMnURkqFDXSygYUJLf1eKzPJYg3uZe+OSIXFdZGz4tY2UUw3pmCgCt+vqMPgPKCDqIUaYdmWFinBBayXjZYylSG8Xzpfh2FSeik0awJCdrLoo03gItBkQkqTxCYxdZJ0S/C6GhHjQbakClkC96ytz2YNe0bo6ys9Rgej3AX5ie7H0e2PwZPEt/RkVotiSA5+hwpokvyIcU1yaDdRLmXU5w1Xml1REKXASz8rVs0N0ghCs+3W+h9OamN0UOb4Tq1txEBt+xmos/oN6OPDfQ9kR8LU2FYcJa0+eQ0Nh4DTQVMuHPqTd0NCCO2qFlfog3C7uGNlV17oiPNTLMSoGOCRnK2wwKjc6/NADcNMYHGY1YyOeLfqtxw6sTouIdYjaKFxmyTLJ3R5+eKa4z5nIbzejbj8+twmxHbiHL9Cn7hfnfkbMn9ZMPZdwdelhqzN7Y= # GITHUB_TOKEN
