language: node_js
node_js:
  - 14
script:
  - yarn install
  - yarn docsPublish
  - zip -r tsdocs.zip docs_html || travis_terminate 1;
deploy:
  - provider: npm
    email: 'support@mapwize.io'
    api_key: '${NPM_TOKEN}'
    tag: '${TRAVIS_TAG}'
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    api_key: '${GITHUB_TOKEN}'
    file: './tsdocs.zip'
    skip_cleanup: true
    on:
      tags: true
env:
  global:
  - secure: cfao98qNBY1KaZdE4HlCT/xINS8PP+BGS1iCgLM/GXTbkwGh5bTYxZNBUN8VXNbNo+E2C/5jl5jG/lSlQngCuU1Ql1iz/57PUvq4C7/wb1hTy696GKsdVu3/oZyVk4vYZTZhXsb7wavugeFd1cZSMCO4l0f6UaKfXtxFJPMbe3RTbM8F3HFu4j9SgaN/YOxcY/PVIckXmDDtl2M0R0Ey+MOs9ILT4mtBIgH5GQ2F0/8zEQclyDl9RRVpAmyo5YX6Mvh4O3Byw/I/w9LGxAj14Tp4TcBpTThKDCMF9RmCiKUzEJt1ATXTH/ipMDatb5oT7AjJsriSyOifl55WO6MPM2QTpqGpjoLp2TDzsdh/gXeTC1O+LK8oUcCoMx5Tufpx2MHIkPn2K8UNzNK5eAhK4DIDhQ6MqO0fIEq/5shTUk64Cp5OqPbVD2N4EWZZn8g/B15lNqyykl6LO2KGJj4Bu1yNqSp0TLGvfOVmrGCShdvPrrnxFsO3R59wE8yX2MlDjz7YF7elQAnm4NjNIyjDAzqwu4EnnQi2P4MH3IVmYUAu0/85cQ1TyG4qprFPl9kZMPBsDO47FU/4Wc5TiX3Itg0mbMLXAYCAZApgGq6rL2nSFqAjirEcKuYAjhdlJL1SRyOcdsZoygzEV2vaRDMU+s9t+ta23BgpB1RvrkGVPVQ= # GITHUB_TOKEN
  - secure: N935u03n/ooWeDVkIgDNvZm+TPHxv42APB291CjMIQoJUkVLJotys3GZY4or2sitCU1PLCuJrW391HLSO1OjYPY66hmQKqcm3lJMFVAmp8L8z9gq4SabApyYtT+VW+QUXmfH+Ww2wXyMfBDfoePLQRCeCUZbbQstGuqqK6ncVnZvSOFRkwtctnPoO10rxajJGweptmnSyQofBb8yKprYpXKYPHdtO24AhqVyvAnqKKCQL2RUv57QHHBR8J1QuTQyhghbWTvmeUZx9pQByoXGuUr901mB5l04Vpk9MV+UDvzacEhpA7+xAX1oHUkC9HDNsL7dFQ8rHumgt6feLDujawrsXKUm90SrXXPiBufRNH5NUmtLuYVtyldVdTSa6OFmQLUY/ILMRWau1TN0ZW5Wbo0cIxz0Z88wgu0yDJZvVFFRwXP55ekbDcS7iXCkUQWXD/NTaJn69ETkrAvMr0BBzv65SfUl/agNLYEUX9qqZW1ud+r/T6RDD/TBJA5rjjf68bFwfdlul1H4h/7JF3BWdMT6GDs31c8/WyrOIiak4TVY4TtZQKwsynrrOsuRmt3jlHmS2oLVud57t9KRotZFNii0R2plWTMSMW/xkhw3hmf2Nn2XHxnYRKbin/78BgPo3h5U+QUhfgJNoGHVMGbGDt2wMos8ZwfblPYZuE3b4ao= # NPM_TOKEN
